"""Add confirmation column to Child

Revision ID: ba9e68004f9b
Revises: f116fe8a895e
Create Date: 2023-08-20 21:35:33.865469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba9e68004f9b'
down_revision = 'f116fe8a895e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmation', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.drop_column('confirmation')

    # ### end Alembic commands ###
