version: "3"
services:
  app:
    image: app
    build:
      context: .
    ports:
      - 8000:8321
    networks:
      - my-network
    volumes:
      - ./:/app
    environment:
      FLASK_ENV: development
      FLASK_APP: kiki.py
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: project1
      MYSQL_PASSWORD: SuperSicher
      MYSQL_DB: flask_app_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_SuperSicher
      MYSQL_DATABASE: project1
      MYSQL_USER: project1
      MYSQL_PASSWORD: SuperSicher
    networks:
      - my-network
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root_password
    ports:
      - 8081:80
    networks:
      - my-network

networks:
  my-network:
