"""Windelwechsel Table entfernt, Child und Activity angepasst

Revision ID: 1e84e1321e8e
Revises: 1825fd7293dc
Create Date: 2023-08-26 15:29:32.385869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e84e1321e8e'
down_revision = '1825fd7293dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('sleep_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('sleep_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('diaper_change', sa.DateTime(), nullable=True))
        batch_op.alter_column('child_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_activity_activity_type')
        batch_op.drop_column('activity_type')
        batch_op.drop_column('description')

    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('group',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_index('ix_child_timestamp')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('confirmation')
        batch_op.drop_column('food')
        batch_op.drop_column('sleep_end')
        batch_op.drop_column('activities')
        batch_op.drop_column('sleep_start')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sleep_start', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('activities', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('sleep_end', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('food', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('confirmation', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_child_timestamp', ['timestamp'], unique=False)
        batch_op.alter_column('group',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=128), nullable=True))
        batch_op.add_column(sa.Column('activity_type', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_index('ix_activity_activity_type', ['activity_type'], unique=False)
        batch_op.alter_column('child_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('diaper_change')
        batch_op.drop_column('sleep_end')
        batch_op.drop_column('sleep_start')
        batch_op.drop_column('food')

    # ### end Alembic commands ###
