"""Activity angepasst

Revision ID: 170070a1e930
Revises: 1e84e1321e8e
Create Date: 2023-08-26 16:15:44.672751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170070a1e930'
down_revision = '1e84e1321e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diaper_change', schema=None) as batch_op:
        batch_op.drop_index('ix_diaper_change_timestamp')

    op.drop_table('diaper_change')
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diaper_change_large', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('diaper_change_small', sa.DateTime(), nullable=True))
        batch_op.drop_column('diaper_change')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diaper_change', sa.DATETIME(), nullable=True))
        batch_op.drop_column('diaper_change_small')
        batch_op.drop_column('diaper_change_large')

    op.create_table('diaper_change',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('change_type', sa.VARCHAR(length=5), nullable=True),
    sa.Column('child_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diaper_change', schema=None) as batch_op:
        batch_op.create_index('ix_diaper_change_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
