"""Windelwechsel hinzugefügt

Revision ID: 658f23541860
Revises: ba9e68004f9b
Create Date: 2023-08-21 20:35:06.203288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '658f23541860'
down_revision = 'ba9e68004f9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diaper_change',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('change_type', sa.String(length=5), nullable=True),
    sa.Column('child_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diaper_change', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diaper_change_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diaper_change', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diaper_change_timestamp'))

    op.drop_table('diaper_change')
    # ### end Alembic commands ###
