"""Anpassung Activity Model

Revision ID: f5f97b384953
Revises: 170070a1e930
Create Date: 2023-08-26 23:56:07.623320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5f97b384953'
down_revision = '170070a1e930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('activity_type')

    # ### end Alembic commands ###
